### ISSUE TITLE
zoneinfo fatal issue

### ISSUE THREAD

**Issue by systec-electronic** [beercan1989/docker-arm-mysql#1] opened 2018-07-03 11:13 UTC
Hi, I have installed you source on my debian machine, but I got an error: 
> root@ctr-700:~/docker-arm-mysql#   docker run -it \
>      -e 'MYSQL_ROOT_PASSWORD=password' \
>      -e 'MYSQL_DATABASE=identity' \
>      -e 'MYSQL_USER=identity' \
>      -e 'MYSQL_PASSWORD=password' \
>      -p '3306:3306' \
>      --name example_mysql \
>      beercan1989/arm-mysql:latest
> 
> device veth30fcf8a entered promiscuous mode
> IPv6: ADDRCONF(NETDEV_UP): veth30fcf8a: link is not ready
> eth0: renamed from vethb83453d
> IPv6: ADDRCONF(NETDEV_CHANGE): veth30fcf8a: link becomes ready
> docker0: port 1(veth30fcf8a) entered forwarding state
> docker0: port 1(veth30fcf8a) entered forwarding state
> MySQL init process in progress...
> MySQL init process in progress...
> Loading timezones into MySQL
> There were fatal errors during processing of zoneinfo directory

could you please help?

**Comment by beercan1989** [comment] 2018-07-03 16:17
Is your Debian machine running on an arm processor?

As I've only ever had this working directly on a Raspberry PI from about 2 years ago.

**Comment by systec-electronic** [comment] 2018-07-04 06:31
Yes I am using also arm processor.
```
#uname -a
Linux 4.1.15-224598-g4522a54-dirty #1 SMP PREEMPT Thu May 17 17:43:55 CEST 2018 armv7l GNU/Linux
```
and 

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.10 (jessie)
Release:        8.10
Codename:       jessie
```

**Comment by beercan1989** [comment] 2018-07-04 16:19
I've managed to reproduce the problem now, seems like the base image `armhf/ubuntu:xenial` has had a few changes since I originally built the image.

Reproduced by building the image from scratch, I'll have a look and see if I can get it building again.

Although the existing images in the docker hub should still work.

**Comment by beercan1989** [comment] 2018-07-04 16:44
One quick work around could actually be to just disable loading of timezones, but may cause other problems down the line.

Just add `-e 'MYSQL_INITDB_SKIP_TZINFO=true'` to the docker run command

**Comment by beercan1989** [comment] 2018-07-04 17:32
So turns out it the base image was just missing a package **tzdata**, installing that package should resolve the problem.

**Comment by beercan1989** [comment] 2018-07-04 17:44
Change merged into master, new images built and pushed into the docker hub.

**Closed by beercan1989** 2018-07-04 17:44 UTC
Labels: bug

**Comment by systec-electronic** [comment] 2018-07-05 06:17
Thanks, the connection and DB work)
